# client discovery configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-85443835.okta.com/oauth2/default
    audience: api://default

# Zipkin configuration - previously not needed because we were not using k8s
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411  # Zipkin endpoint defined in k8s
